# For more information: https://laravel.com/docs/sail
version: '3'
services:
    php.dev:
        build:
            context: ./docker
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/app'
        networks:
            - sail
networks:
    sail:
        driver: bridge
